# Generated by Django 6.0.7 on 2026-07-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('repuesto', 'Repuesto'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_tipo', models.CharField(choices=[('celular', 'Celular'), ('joystick', 'Joystick'), ('ps4', 'PS4'), ('notebook', 'Notebook')], max_length=20, verbose_name='tipo de dispositivo')),
                ('descripcion_problema', models.TextField(verbose_name='descripción del problema')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_reparacion', 'En reparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='recibido', max_length=20)),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio acordado')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
