# Generated by Django 6.0.7 on 2026-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='proveedor'),
        ),
    ]
