# Generated by Django 6.0.7 on 2026-07-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_gasto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='taller.trabajo', verbose_name='trabajo asociado'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de pago'),
        ),
    ]
