# Generated by Django 6.0.7 on 2026-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_gasto_trabajo_trabajo_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('repuesto', 'Repuesto'), ('herramienta', 'Herramienta'), ('taller', 'Taller'), ('otro', 'Otro')], max_length=20),
        ),
    ]
