# Generated by Django 6.0.7 on 2026-09-04 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_modelo_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='precio_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')], verbose_name='precio acordado'),
        ),
    ]
