# Generated by Django 6.0.7 on 2026-09-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_alter_gasto_monto_alter_pago_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='trabajo',
        ),
    ]
