# Generated by Django 6.0.7 on 2026-09-07 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_gasto_catalogos_y_repuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')], verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')], verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')], verbose_name='precio unitario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')], verbose_name='monto'),
        ),
    ]
