# Generated by Django 6.0.7 on 2026-09-07 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_ajustes_finales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_generados', to='taller.trabajo', verbose_name='trabajo asociado'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='detalle',
            field=models.TextField(blank=True, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.marca', verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.modelo', verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tercerizado_detalle',
            field=models.CharField(blank=True, max_length=255, verbose_name='detalle de tercerización'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tercerizado_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Este monto no puede ser negativo.')], verbose_name='monto tercerizado'),
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')], verbose_name='cantidad')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='taller.gasto', verbose_name='repuesto')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='taller.trabajo', verbose_name='trabajo')),
            ],
            options={
                'verbose_name': 'repuesto usado',
                'verbose_name_plural': 'repuestos usados',
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.tercero', verbose_name='tercero'),
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_reparacion', to='taller.tipodispositivo', verbose_name='tipo de dispositivo')),
            ],
            options={
                'verbose_name': 'tipo de reparación',
                'verbose_name_plural': 'tipos de reparación',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipo_reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.tiporeparacion', verbose_name='tipo de reparación'),
        ),
    ]
