# Generated by Django 6.0.7 on 2026-09-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0016_limpiar_fecha_entrega_inconsistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generados', to='taller.trabajo', verbose_name='trabajo asociado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='taller.trabajo', verbose_name='trabajo'),
        ),
    ]
