# Generated by Django 6.0.7 on 2026-09-12 20:59

from django.db import migrations


def borrar_tercerizados_huerfanos(apps, schema_editor):
    """Antes de esta tanda, borrar un Trabajo dejaba su Gasto "Tercerizado"
    vivo con trabajo=NULL (era SET_NULL): quedaba huérfano, no se podía
    borrar desde Gastos y seguía sumando en Balance para siempre. Ahora que
    ese vínculo es CASCADE, limpiamos los que ya hayan quedado así."""
    Gasto = apps.get_model('taller', 'Gasto')
    Gasto.objects.filter(categoria__nombre='Tercerizado', trabajo__isnull=True).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_cascade_borrado_trabajo'),
    ]

    operations = [
        migrations.RunPython(borrar_tercerizados_huerfanos, noop),
    ]
