# Generated by Django 6.0.7 on 2026-09-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0020_migrar_detalle_a_descripcion_problema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='detalle',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion_problema',
            field=models.TextField(blank=True, verbose_name='descripción del problema'),
        ),
    ]
